name: Deploy to gh-pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build
        run: |
          npm install
          npm run deploy

      - name: Deploy to gh-pages
        env:
          TARGET_FOLDER: 'build'
          TARGET_BRANCH: 'gh-pages'
        run: |
          git config --global user.name 'autom'
          git config --global user.email 'profcoder69420@gmail.com'
          git fetch
          git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
          git rm -rf .
          mkdir -p $TARGET_FOLDER
          cp -r ../$TARGET_FOLDER/* .
          git add -A
          git commit -m "Deploy to gh-pages"
          git push origin $TARGET_BRANCH

      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.BO_MAY_BEO_ME_MAY_GAY_KO_AI_HOI }}" https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds
