name: Deploy to gh-pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build
        run: |
          npm update
          npm install
          git config user.email "${{ secrets.NO_ONE_KNOWS }}"
          git config user.name "profcoder69420"
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.BO_MAY_BEO_ME_MAY_GAY_KO_AI_HOI }}

      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.BO_MAY_BEO_ME_MAY_GAY_KO_AI_HOI }}" https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds
